import type { SketchPoint } from "../drawing";
export const drawingConstraintKinds = [
  "coincident",
  "horizontal",
  "vertical",
  "parallel",
  "perpendicular",
  "concentric",
  "equal",
  "midpoint",
  "tangent",
  "curvature",
  "normal",
  "symmetric",
  "quadrant",
  "ellipse-shape",
  "ellipse-locus",
  "spline-shape",
  "pattern",
  "offset",
  "slot",
  "distance",
  "horizontal-distance",
  "vertical-distance",
  "length",
  "radius",
  "diameter",
  "angle",
  "fix",
] as const;
export type DrawingConstraintKind = (typeof drawingConstraintKinds)[number];
/** References use contour/segment indices; deleting geometry must remap or remove its constraints. */
export interface SketchEntityRef {
  contour: number;
  /** Stable ID in the parent projection's resolved source; contour is -1 when persisted. */
  projectedContourId?: string;
  /** Stable segment identity; index is a fallback only for legacy references without an ID. */
  segmentId?: string;
  /** Stable path vertex identity, independent of edge ordering. */
  vertexId?: string;
  kind: "point" | "line" | "circle" | "arc" | "ellipse" | "curve" | "contour";
  index?: number;
  control?: 0 | 1;
  /** Positive endpoint-relative scale preserving a control vector through subdivision. */
  controlScale?: number;
  /** Fixed finite curve parameter, used by tangent/curvature contact references. */
  parameter?: number;
  /** Allow the solver to move this relation contact within the finite segment. */
  sliding?: boolean;
}
export interface DrawingConstraint {
  id: string;
  kind: DrawingConstraintKind;
  a: SketchEntityRef;
  b?: SketchEntityRef;
  /** Live symmetry line; participates in geometry reference remapping. */
  axis?: SketchEntityRef;
  /** Ellipse local-axis endpoint: 0,+X; 1,+Y; 2,-X; 3,-Y. */
  quadrant?: 0 | 1 | 2 | 3;
  /** Match spline control points in reverse traversal order for symmetry. */
  splineReversed?: boolean;
  /** Positive relative knot-span intervals for an explicitly parameterized fit spline. */
  splineSpanIntervals?: number[];
  value?: number;
  /** Typed formula; value is its validated canonical mm/degree cache. */
  valueExpression?: string;
  /** Read-only measurement, contributes no solver equations. */
  reference?: boolean;
  /** Dimension driver constraint ID; mutually exclusive with a literal value. */
  valueFrom?: string;
  /** Orientation of an angular driver link; omitted means +1. */
  valueSign?: 1 | -1;
  /** Dimensionless nonzero multiplier of the linked driver; default 1. */
  valueScale?: number;
  /** Additive linked offset in canonical millimeters/degrees; default 0. */
  valueOffset?: number;
  point?: SketchPoint;
  /** Fixed instance transform; translation is in millimeters. Generated by pattern tools. */
  /** Retained slot metadata when instance geometry is suppressed. */
  patternSuppression?: { id?: string; construction?: boolean; hole?: boolean };
  patternGroup?: string;
  patternInstance?: number;
  transform?: import("../curves/similarity").SketchTransform;
  /** Closed slot boundary relative to its source centerline. */
  slotBoundary?: "inner" | "outer";
  tangentMode?: "external" | "internal";
}
