enum StudioPreferenceKey {
  static let settingsSelectedTab = "settingsSelectedTab"
  static let workspaceRootPath = "workspaceRootPath"
  static let workspaceRootBookmark = "workspaceRootBookmark"

  static let viewportAppearance = "viewportAppearance"
  static let viewportNavigationProfile = "viewportNavigationProfile"
  static let viewportCustomRotateDrag = "viewportCustomRotateDrag"
  static let viewportCustomPanDrag = "viewportCustomPanDrag"
  static let viewportCustomPreciseZoomDrag = "viewportCustomPreciseZoomDrag"
  static let viewportOrbitSpeed = "viewportOrbitSpeed"
  static let viewportPanSpeed = "viewportPanSpeed"
  static let viewportZoomSpeed = "viewportZoomSpeed"
  static let viewportReversesWheelZoom = "viewportReversesWheelZoom"
  static let viewportRenderStyle = "viewportRenderStyle"
  static let viewportEdgeDisplay = "viewportEdgeDisplay"
  static let viewportLightingPreset = "viewportLightingPreset"
  static let viewportMaterialFinish = "viewportMaterialFinish"
  static let viewportReflectionMode = "viewportReflectionMode"
  static let viewportShowsShadows = "viewportShowsShadows"
  static let viewportFieldOfViewDegrees = "viewportFieldOfViewDegrees"
  static let viewportLightingIntensity = "viewportLightingIntensity"
  static let viewportEnvironmentPreset = "viewportEnvironmentPreset"
  static let viewportEnvironmentRotationDegrees = "viewportEnvironmentRotationDegrees"
  static let viewportRenderQuality = "viewportRenderQuality"
}
